version: '3.8'

services:
  app:
    image: 'dmsapi:latest'
    build:
      context: ./api
    container_name: dmsapi
    ports:
      - 8081:8081
  client:
    image: dmsapp
    build:
      context: ./dmsapp
    container_name: dmsapp
    ports:
      - "80:80"