spring.application.name=ocr
server.port=8082

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=manual


broker.exchange = samples
broker.routingKey = samples.default
broker.routingKeyOcrComplete = samples.default2