version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"                  # Backend listens on port 8081
    volumes:
      - ./Backend/src:/app/src
      - ./Backend/target:/app/target  # Mount the target directory so changes are reflected without rebuilding
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./Frontend/build:/usr/share/nginx/html  # Mount the frontend build folder for serving by Nginx
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
      - ./Frontend/build:/usr/share/nginx/html    # Serve built frontend via Nginx
    ports:
      - "80:80"                                  # Nginx listens on port 80
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
