version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"                  # Backend listens on port 8081
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"                  # Frontend listens on port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
